apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: consumer
    spec:
      containers:
        - name: consumer
          #image: bindu5483/consummerdocker
          image: dockerhub.tryexa.com/scmxpert/consumerdocker
          imagePullPolicy: IfNotPresent

          env:
            - name: bootstrap_servers
              valueFrom:
                secretKeyRef:
                  name: bootstrapip
                  key: bootstrapserver
            - name: device_data
              valueFrom:
                secretKeyRef:
                  name: devicedata
                  key: device_data
            - name: mongo_uri
              valueFrom:
                secretKeyRef:
                  name: mongouri
                  key: uri
                  
            - name: username
              valueFrom:
                secretKeyRef:
                  name: sslcred
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: sslcred
                  key: password      
                  
      imagePullSecrets:
        - name: regcred   
